import 'food_item.dart';

const foodList = [
  FoodItem(
    title: 'Гречка',
    description: 'Король сложных углеводов. Идеальна для долгой энергии, сытости и стабильного уровня сахара в крови.',
    category: 'Крупы',
    calories: 343,
    bzhu: 'Б: 12.6г | Ж: 3.3г | У: 62.1г',
    rating: 9.5,
    imagePath: 'assets/images/food1.jpg',
  ),
  FoodItem(
    title: 'Овсянка',
    description: 'Богата бета-глюканом, улучшает пищеварение, снижает холестерин и даёт долгое чувство сытости.',
    category: 'Крупы',
    calories: 342,
    bzhu: 'Б: 12.3г | Ж: 6.1г | У: 59.5г',
    rating: 9.0,
    imagePath: 'assets/images/food2.jpg',
  ),
  FoodItem(
    title: 'Куриная грудка',
    description: 'Диетический источник чистого белка с минимальным содержанием жира. Основа рациона спортсменов.',
    category: 'Белок',
    calories: 110,
    bzhu: 'Б: 23.6г | Ж: 1.9г | У: 0.4г',
    rating: 9.3,
    imagePath: 'assets/images/food3.jpg',
  ),
  FoodItem(
    title: 'Творог 5%',
    description: 'Отличный источник казеина (медленного белка) и кальция для здоровья костей и восстановления мышц.',
    category: 'Молочное',
    calories: 121,
    bzhu: 'Б: 17.2г | Ж: 5.0г | У: 1.8г',
    rating: 8.8,
    imagePath: 'assets/images/food4.jpg',
  ),
  FoodItem(
    title: 'Брокколи',
    description: 'Суперфуд с высоким содержанием витаминов C, K, фолиевой кислоты и мощных антиоксидантов.',
    category: 'Овощи',
    calories: 34,
    bzhu: 'Б: 2.8г | Ж: 0.4г | У: 6.6г',
    rating: 9.1,
    imagePath: 'assets/images/food5.jpg',
  ),
  FoodItem(
    title: 'Лосось',
    description: 'Ценный источник Омега-3 жирных кислот, витамина D и высококачественного легкоусвояемого белка.',
    category: 'Рыба',
    calories: 208,
    bzhu: 'Б: 20.0г | Ж: 13.0г | У: 0г',
    rating: 9.4,
    imagePath: 'assets/images/food6.jpg',
  ),
  FoodItem(
    title: 'Авокадо',
    description: 'Полезные мононенасыщенные жиры, калий и клетчатка для здоровья сердца и метаболизма.',
    category: 'Фрукты',
    calories: 160,
    bzhu: 'Б: 2.0г | Ж: 14.7г | У: 8.5г',
    rating: 8.9,
    imagePath: 'assets/images/food7.jpg',
  ),
  FoodItem(
    title: 'Яйца куриные',
    description: 'Идеальный аминокислотный профиль, витамины группы B, холин и легкоусвояемые жиры.',
    category: 'Белок',
    calories: 155,
    bzhu: 'Б: 12.6г | Ж: 10.9г | У: 0.7г',
    rating: 9.2,
    imagePath: 'assets/images/food8.jpg',
  ),
  FoodItem(
    title: 'Нут (турецкий горох)',
    description: 'Растительный белок и клетчатка, идеален для контроля аппетита и поддержки микрофлоры.',
    category: 'Бобовые',
    calories: 364,
    bzhu: 'Б: 19.0г | Ж: 6.0г | У: 60.7г',
    rating: 8.7,
    imagePath: 'assets/images/food9.jpg',
  ),
  FoodItem(
    title: 'Шпинат',
    description: 'Кладезь железа, магния, фолиевой кислоты и витаминов для иммунитета и энергии.',
    category: 'Зелень',
    calories: 23,
    bzhu: 'Б: 2.9г | Ж: 0.4г | У: 3.6г',
    rating: 9.0,
    imagePath: 'assets/images/food10.jpg',
  ),
];